plugin 'cocoapods-acknowledgements'

target "Demo Project" do
	pod "CPDAcknowledgements", :path => "../CPDAcknowledgements.podspec"

	# These pods are used only for giving us some data
	pod "ORStackView"
	pod "IRFEmojiCheatSheet"

	target "Demo ProjectTests" do
    inherit! :search_paths

    pod 'Specta',      '~> 1.0'
    pod 'Expecta',     '~> 1.0'
    pod 'OCMockito',   '~> 1.0'
  end
end
